require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - bin/bundle
    - vendor/**/*
    - node_modules/**/*
    - spec/rails_helper.rb
    - db/schema.rb
    - db/migrate/*
    - Gemfile

Lint/UselessAssignment:
  Exclude:
    - db/seeds.rb

# Fixed indentation means that we don't get multi-line
# diffs because a single argument was added and all the
# rest of them got moved around.
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

# Has to be explicitly enabled. Checks there are no spaces
# between an object and method like `foo . do_stuff`
Layout/SpaceAroundMethodCallOperator:
  Enabled: true

# You almost never want to raise Exception rather than StandardError
Lint/RaiseException:
  Enabled: true

# Warn when overriding native methods of Struct (usually by mistake)
Lint/StructNewOverride:
  Enabled: true

# New Style cops which need explicitly configuring
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/ExponentialNotation:
  Enabled: false

# Because `and` and `or`, while reading better, also don't
# short circuit the conditional, and so are liable to introduce
# side effects where not expected.
Style/AndOr:
  EnforcedStyle: conditionals

# Purely cosmetic, this is an easier style to read.
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

# Enforce consistency in how we do map/reduce operations.
Style/CollectionMethods:
  Enabled: true

# Because life is too short to document every single accessor
# as "read accessor for foo".
Style/Documentation:
  Enabled: false

# Mostly historical, we have a lot of places that really care
# about whether its a boolean or just truthy/falsey.
Style/DoubleNegation:
  Enabled: false

# Not all two character words are actually unclear in context
Naming/MethodParameterName:
  AllowedNames:
    - io
    - id
    - to
    - by
    - on
    - in
    - at
    - ip
    - db
    - t     # Time
    - ev    # Event

# { a: "foo" } syntax is usually preferable, but mixing
# symbol and string keys is a path to misery when trying
# to work out why something broke.
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

# Just cosmetic preference
Style/PercentQLiterals:
  EnforcedStyle: upper_case_q

# The performance benefit of single quoting doesn't justify
# the contortions involved in changing your quotation style
# because you need to interpolate something.
Style/StringLiterals:
  EnforcedStyle: single_quotes

# Prevent annoying breakages because you forgot to add a comma
Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

# We're not programming on 1970s dumb terminals, so can accommodate
# line lengths over 75 characters. 120 is a good limit to ensure
# two editor panes can be comfortably open side by side on modern
# displays.
Layout/LineLength:
  Max: 120
  Exclude:
  - 'db/schema.rb'
  - 'db/migrate/*.rb'
  - 'bin/*'
  - 'config/initializers/devise.rb'

# The default of 10 lines is a bit extreme, and tends to result in
# methods being split for the sake of pleasing Rubocop, at the cost
# clarity.
Metrics/MethodLength:
  Max: 20
  Exclude:
  - 'db/migrate/*.rb'
  - 'spec/**/*_spec.rb'

# Likewise, lets not create new classes just to shut Rubocop up.
Metrics/ClassLength:
  Max: 200
  Exclude:
  - 'db/migrate/*.rb'

# Don't have Rubocop making noise on autogenerated files.
Layout/EmptyLinesAroundBlockBody:
  Exclude:
  - "db/schema.rb"

Style/Encoding:
  Enabled: true
  Exclude:
  - "db/schema.rb"

Layout/ExtraSpacing:
  Exclude:
  - "db/schema.rb"

Naming/FileName:
  ExpectMatchingDefinition: true
  Exclude:
  - 'bin/**/*'
  - 'lib/tasks/**/*.rb'
  - 'spec/**/*_spec.rb'
  - 'spec/support/**/*.rb'
  - 'spec/*_helper.rb'
  - 'spec/factories/**/*.rb'
  - 'features/step_definitions/**/*.rb'
  - 'features/support/**/*.rb'
  - 'config/**/*.rb'
  - 'config.ru'
  - 'db/migrate/*.rb'
  - 'db/schema.rb'
  - 'db/seeds.rb'
  - 'app/views/*/*.jbuilder'

Style/NumericLiterals:
  Exclude:
  - "db/schema.rb"

Style/WordArray:
  Exclude:
  - "db/schema.rb"

Metrics/AbcSize:
  Exclude:
  - 'db/migrate/*.rb'

Metrics/BlockLength:
  Exclude:
  - 'db/schema.rb'
  - 'spec/**/*_spec.rb'
  - 'Guardfile'
  - 'config/environments/development.rb'
  - 'config/environments/production.rb'

Layout/EmptyLineAfterMagicComment:
  Exclude:
    - 'db/schema.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/**/*.rb'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/**/*.rb'

RSpec/MultipleMemoizedHelpers:
  Max: 15

RSpec/SubjectStub:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/**/*.rb'
    - 'features/**/*.rb'
    - 'app/views/*/*.jbuilder'
Layout/IndentationConsistency:
  Exclude:
    - 'db/seeds.rb'
